### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by rilokex** [pbellino/CNFreader#2] opened 2024-07-08 05:34 UTC
I really appreciate your effort in developing this module. However, I'm encountering trouble importing the module, and I'm unsure of the reasons for the error. Could you please assist me with this? Thank you in advance!

![Screenshot 2024-07-08 133138](https://github.com/pbellino/CNFreader/assets/57588909/a0c2e34c-f132-4ec8-b815-8ea146489bbf)

**Comment by Squawk322** [comment] 2024-07-08 11:12
Please provide a *.cnf file you are using to test it. The module works fine with the files I'm using.

**Comment by rilokex** [comment] 2024-07-08 11:24
Thank you for replying! The module works fine with your example files, which really confuses me regarding my .cnf file. I've attached the files. Thank you very much!
[zip.zip](https://github.com/user-attachments/files/16126887/zip.zip)

**Comment by Squawk322** [comment] 2024-07-08 11:41
Just for reference, what kind of information your *.cnf file carry?

**Comment by rilokex** [comment] 2024-07-08 11:50
This is a file containing counts of gamma-ray spectra with 1024 channels.
When I use the R package 'gamma', I obtain information such as live time, channel number, energy, count, and sample details.

**Comment by pbellino** [comment] 2024-07-08 16:56
There was an error in reading the "Sample units". I think that the issue is now fixed. Plead check the new commit and let me know if you find any errors.
Thank you for the feedback

**Comment by rilokex** [comment] 2024-07-09 15:21
it works great! Thank you very much!

**Closed as completed** 2024-07-09 16:15 UTC
